<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Successfully</name>
   <tag></tag>
   <elementGuidId>2a2fa57e-ab77-4d93-96f5-a2a0de1f1130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-1-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toast-1-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a472fd2-661a-4e2a-b6dd-1eb85b8ac258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>870275d3-85d7-4f08-a296-b572ee669fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-1-title</value>
      <webElementGuid>38e5caff-0919-4e12-958c-f4f2c021151b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert__title css-tidvy5</value>
      <webElementGuid>57291687-4db9-423f-aa33-d52a714d9b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully</value>
      <webElementGuid>2f9f3f10-2e62-4c19-9f7d-6850cb875c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-1-title&quot;)</value>
      <webElementGuid>fb78033f-4ab9-4402-83eb-1028c2e71bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-1-title']</value>
      <webElementGuid>4d9e77e3-44a5-45ad-a350-03bd0a746818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-1']/div/div</value>
      <webElementGuid>8b1677d9-0d90-4669-a176-6936e43850e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open React Query Devtools'])[1]/following::div[7]</value>
      <webElementGuid>37e2d768-9d4c-4798-ab3a-f06287d78d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[7]</value>
      <webElementGuid>2ce9f85b-12ac-4e90-b0c1-06d139d3f630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You item already in shopping cart'])[1]/preceding::div[1]</value>
      <webElementGuid>d96d61e9-1532-4e47-9564-37586debbfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-1-title', '&quot;', ')')])[1]/preceding::div[7]</value>
      <webElementGuid>7d34ae23-f4bb-486f-a6ca-a17785ae6f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Successfully']/parent::*</value>
      <webElementGuid>b7487986-7ee1-4d2a-aefb-950147cab61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>3c79d38e-6d9f-443f-b15c-924415c0acc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-1-title' and (text() = 'Successfully' or . = 'Successfully')]</value>
      <webElementGuid>527006ca-ff3a-43aa-afd0-d41122bb8aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
