<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_by category_chakra-image css-lxd7e7</name>
   <tag></tag>
   <elementGuidId>0eeec7e1-91b6-4ec7-ad33-fe863e4b24ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[3]/div[2]/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.chakra-image.css-lxd7e7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bda7da61-4247-4d78-bcdd-c01f04e354bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg</value>
      <webElementGuid>8f2a3066-5c7e-461b-8dc4-06ab1eb92596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-image css-lxd7e7</value>
      <webElementGuid>a91d6a6b-c796-4264-8b6c-4f97933b6539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-1avrgqm&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-cv59qw&quot;]/div[@class=&quot;css-yyiqbu&quot;]/div[@class=&quot;css-1w2pp6y&quot;]/div[@class=&quot;chakra-card css-e5f81e&quot;]/a[1]/div[@class=&quot;chakra-card__body css-ao8dev&quot;]/img[@class=&quot;chakra-image css-lxd7e7&quot;]</value>
      <webElementGuid>32268d08-685b-4b27-9525-c56396deabee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[3]/div[2]/div/div/a/div/img</value>
      <webElementGuid>e92daa0b-1a95-4a6a-9642-108e5f6bfa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg')]</value>
      <webElementGuid>79b1dd90-c261-4d26-9d7d-b949d89c95f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>11b80a85-7997-48ae-9e38-c40e5c6cee5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg']</value>
      <webElementGuid>7247f33e-ee79-4054-a1d1-cd41a0a48542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
