<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Local specialtys areasThe best offer th_421523</name>
   <tag></tag>
   <elementGuidId>b54065f8-df6b-4d31-9cc0-f6adebd9d81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-j74872</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08e25482-e5fb-44e9-9afb-046a8f829fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j74872</value>
      <webElementGuid>72fe2aa4-9ab8-4f73-a5a9-006313d3cf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local specialty's areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: @#$%^&amp;*() </value>
      <webElementGuid>6e0e4148-8bd2-4bf6-b1d0-54713c897a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]</value>
      <webElementGuid>bb6c4811-ae4a-430d-9c63-29dc04df859e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]</value>
      <webElementGuid>eeec7bf3-fb7a-4062-9070-34148f2be650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>216dd199-aa96-4e22-8e01-a257df8f37f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: @#$%^&amp;*() &quot;) or . = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: @#$%^&amp;*() &quot;))]</value>
      <webElementGuid>a4695647-7786-422c-92cb-555bbd287a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
