<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_allKhMinhhonag</name>
   <tag></tag>
   <elementGuidId>b04544e1-4cdf-4605-b1ca-c18c71d929f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1w0dmnq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0d50790-2fe3-4077-b2dc-0b4e3afa0f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1w0dmnq</value>
      <webElementGuid>0909a9f6-f984-4cea-8cff-dbcdb2c86317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>allKhôMinhhonag</value>
      <webElementGuid>077a93d0-f2a7-42c1-bf6c-4d75af96e8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-1w0dmnq&quot;]</value>
      <webElementGuid>3effbf89-4f44-4e3f-a94e-8f467932b0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]</value>
      <webElementGuid>2785a51b-bb79-4642-b152-f8e1480c9d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The best offer that we offer to the world'])[1]/following::div[1]</value>
      <webElementGuid>2fd3523a-9051-4d7b-a73b-cd3d8c19e8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Local specialty', &quot;'&quot;, 's areas')])[1]/following::div[1]</value>
      <webElementGuid>c7fa28ed-4b37-42aa-8a8f-a305ff434ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>7436ab8d-42e7-4ab7-ba08-4aa83106842d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'allKhôMinhhonag' or . = 'allKhôMinhhonag')]</value>
      <webElementGuid>4c6826c4-4249-47a4-9f3b-a4f96eef1b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
