<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Local specialtys areasThe best offer th_178a87 (1)</name>
   <tag></tag>
   <elementGuidId>1bb7e11e-d914-46c8-b05d-19fe7bc9d64a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-j74872</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2783dada-b4ae-40d7-8a00-a8fa9316bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j74872</value>
      <webElementGuid>83ef278e-807d-43d4-b256-2d5369b28318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local specialty's areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫30.000 ₫40.000 ₫800.000 ₫12bbb Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫aaaaa Minh MInh Minh800.000 ₫aaaaa Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫balafghjklalalal800.000 ₫balalalalal800.000 ₫balalalalal800.000 ₫Minh MInh Minh800.000 ₫1232122</value>
      <webElementGuid>4512baa0-b221-481f-9a2c-a4ff82185a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]</value>
      <webElementGuid>671fdfdf-fef1-46ef-a502-f63d4c648edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]</value>
      <webElementGuid>1e02d7f7-6c54-4d74-9133-1cd5858adaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>14d53b99-bf22-4612-9e0b-e33878b9231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫30.000 ₫40.000 ₫800.000 ₫12bbb Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫aaaaa Minh MInh Minh800.000 ₫aaaaa Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫balafghjklalalal800.000 ₫balalalalal800.000 ₫balalalalal800.000 ₫Minh MInh Minh800.000 ₫1232122&quot;) or . = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallKhôMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫30.000 ₫40.000 ₫800.000 ₫12bbb Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫aaaaa Minh MInh Minh800.000 ₫aaaaa Minh MInh Minh  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris  eleifend leo. dsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris lacerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifenddsfsd habitant mest. Mauris placerat eleifend800.000 ₫balafghjklalalal800.000 ₫balalalalal800.000 ₫balalalalal800.000 ₫Minh MInh Minh800.000 ₫1232122&quot;))]</value>
      <webElementGuid>5f2a5586-a6c2-437b-b00e-27045617bf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
