<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Last Name can not include number and sp_257390</name>
   <tag></tag>
   <elementGuidId>e4bc185d-b5f2-4231-9e10-a3beb4100f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-:r6:-feedback']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a2cc3b5-2b3e-47fd-8ea8-2365cf50a243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r6:-feedback</value>
      <webElementGuid>29e34f2b-dff0-4d4b-b9b6-f18a022041a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>767a373d-0891-4538-803b-d94ea3a95c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-502kp3</value>
      <webElementGuid>63cbb7b6-66e5-4f99-96f0-c1a1d3377b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name can not include number and special characters </value>
      <webElementGuid>5a38615e-7937-4198-8938-c6fc4aae94b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r6:-feedback&quot;)</value>
      <webElementGuid>c7cd2cb3-66bb-4549-9a81-fe519c4fbab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-:r6:-feedback']</value>
      <webElementGuid>558c0fc8-3972-412e-9b45-efeaa3d06b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>e5ec6080-024d-44e7-a76c-001d5402449f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[2]</value>
      <webElementGuid>78a21048-75fd-4e58-8cd7-e58366df7cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name can not include numbers and special characters'])[1]/following::div[3]</value>
      <webElementGuid>0e01d645-a505-4f34-9a88-0989e25a1839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[1]</value>
      <webElementGuid>67105595-79a2-42f4-9ce3-7fe8e63c69b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email is required'])[1]/preceding::div[2]</value>
      <webElementGuid>89060c6c-37fe-44b4-a1ce-2832f184a343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last Name can not include number and special characters']/parent::*</value>
      <webElementGuid>d3d34953-6ad0-4e62-ba2f-7a249690c8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>c2319143-2b4d-4f2e-977d-da3a6d5aad9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-:r6:-feedback' and (text() = 'Last Name can not include number and special characters ' or . = 'Last Name can not include number and special characters ')]</value>
      <webElementGuid>d838cbd4-0024-424d-aa18-7db9fd951b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
