<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Province is required</name>
   <tag></tag>
   <elementGuidId>304c826e-1ae2-4340-8cd5-53db200c8605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-:r9:-feedback']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1d3b3c8-0483-42d0-96ae-faf2361dfddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r9:-feedback</value>
      <webElementGuid>88c972fb-4b48-490c-b56d-7c97f7ace23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>848bd0dc-927f-461c-bb9c-de072be0993b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-502kp3</value>
      <webElementGuid>d22128ae-2fb9-43e0-855a-c5d28aa5168a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Province is required</value>
      <webElementGuid>f7243525-d272-4e1f-9b2a-e40261b7e5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r9:-feedback&quot;)</value>
      <webElementGuid>aacd51a4-c2b2-4c33-afc6-a1ee5aef9f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-:r9:-feedback']</value>
      <webElementGuid>28b526bd-0ad5-4b05-abd6-8f30ef06b043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>88bbd102-a7f5-4a75-ba6c-6ac311174ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Province/City'])[1]/following::div[3]</value>
      <webElementGuid>08790ec6-a191-4aa1-a96d-336aab4425da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shipping details'])[1]/following::div[6]</value>
      <webElementGuid>10a26f5d-1847-44e9-8a5b-dab17306eb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/preceding::div[1]</value>
      <webElementGuid>f6cb7fff-f2a8-4445-8823-b5f06afee05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District is required'])[1]/preceding::div[3]</value>
      <webElementGuid>f0e1884e-91ac-40ce-a7df-0deab02b4cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Province is required']/parent::*</value>
      <webElementGuid>63e05ead-9251-4a61-b9d8-50944a336422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>1c0eb83e-3628-4f4d-9953-384f8efc495f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-:r9:-feedback' and (text() = 'Province is required' or . = 'Province is required')]</value>
      <webElementGuid>70fd860e-24a1-4cdb-96e8-4a373eed3550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
