<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SuccessfullyYour Coupon is applied succ_992caa</name>
   <tag></tag>
   <elementGuidId>57dcedb2-ed06-4039-ac68-19ef047c3b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toast-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>148d0780-6297-4448-b8fe-c4f429c284b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>c92b7e44-9f5e-4ade-8b3c-40075a91f568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-2</value>
      <webElementGuid>995de393-f051-4e3f-a2c3-887e72582b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-qret8q</value>
      <webElementGuid>03eff146-3e85-42fd-ba96-41faf769e495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuccessfullyYour Coupon is applied successfully</value>
      <webElementGuid>43f12d06-95ce-45d5-bc98-3fa3d8d89ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-2&quot;)</value>
      <webElementGuid>fff31fc8-391a-4628-8d76-72cadf36d45a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-2']</value>
      <webElementGuid>2d1287c1-34bd-4488-a837-01f426d3e165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-toast-manager-top']/div/div/div</value>
      <webElementGuid>3303035f-7670-472c-b72f-dadf09ffb850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open React Query Devtools'])[1]/following::div[5]</value>
      <webElementGuid>d6b7a56b-5028-4010-91e4-6fff271ad8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[5]</value>
      <webElementGuid>da06dda6-a902-40d8-9fcf-e831f8dfeb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>993a9a90-7771-4e88-a686-6278f2425825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-2' and (text() = 'SuccessfullyYour Coupon is applied successfully' or . = 'SuccessfullyYour Coupon is applied successfully')]</value>
      <webElementGuid>ab8b1bbd-1f00-43ef-8dea-a0dd139db6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
