<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First Name can not include numbers and _fa2194</name>
   <tag></tag>
   <elementGuidId>bf775b0f-244e-4817-9db1-218d0e9b1820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-:r5:-feedback']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0b53144-59af-4cf2-bf16-b76350317254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r5:-feedback</value>
      <webElementGuid>50c3c7ea-06e0-4cb1-87cb-f39aee24b23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>43781ea2-f1dc-492a-88fd-fa772afbcee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-502kp3</value>
      <webElementGuid>6fffea85-87ec-42b3-8edd-ab4ceff50fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name can not include numbers and special characters</value>
      <webElementGuid>bfeca113-b072-42c5-8151-6a77efe4779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r5:-feedback&quot;)</value>
      <webElementGuid>a865b205-363d-48b7-b6c4-ca85a6469f77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-:r5:-feedback']</value>
      <webElementGuid>67ea615f-4a11-4ad9-879a-87437cf053db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>f8be9c02-08ec-4800-8d58-2c79159a9645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::div[2]</value>
      <webElementGuid>4ce3e608-4e81-45cb-a22c-d438378da5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presonal details'])[1]/following::div[5]</value>
      <webElementGuid>f97491e4-edbe-4a2c-b8c0-18fd0bfbf02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::div[1]</value>
      <webElementGuid>45502358-b52b-49e8-afed-720f261d0154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name is required'])[1]/preceding::div[2]</value>
      <webElementGuid>6da1706d-7718-4109-9015-82ddbbe87849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First Name can not include numbers and special characters']/parent::*</value>
      <webElementGuid>26b8e550-9ca8-4fb6-a6f9-196e476c1e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>1d7a74a7-9728-4ebc-a89c-45caafc88436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-:r5:-feedback' and (text() = 'First Name can not include numbers and special characters' or . = 'First Name can not include numbers and special characters')]</value>
      <webElementGuid>b153e42f-2f4f-4819-9b8c-7ebdbfa67145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
