<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardX Pha LongX T Ngi Ch_4e15e9</name>
   <tag></tag>
   <elementGuidId>b873497b-ce51-4bb8-bda6-502d25649e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>91b46e86-eeb2-42a0-bfc3-603f1b3a7d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>87e22c5b-6ded-43e0-8551-3d607c0e15d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>78f8ed2b-2047-4a32-9a26-1e2bddd44f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>434142a3-c2c8-4f42-bf86-8ed277823b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d87266b-a6a5-48f7-8dc2-c706bae86c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-:rb:-feedback</value>
      <webElementGuid>1be1bb90-bbb5-47d1-a950-a4a3acdfb96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardXã Pha LongXã Tả Ngải ChồXã Tung Chung PhốThị trấn Mường KhươngXã Dìn ChinXã Tả Gia KhâuXã Nậm ChảyXã Nấm LưXã Lùng Khấu NhinXã Thanh BìnhXã Cao SơnXã Lùng VaiXã Bản LầuXã La Pan TẩnXã Tả ThàngXã Bản Sen</value>
      <webElementGuid>88df10ed-f512-4fe8-be24-abf6bedc9988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>0fbcb630-a391-457b-98ea-398331f546ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>dd4075ee-bd5b-4284-9182-ee15b3842fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>20abea23-444d-4f5a-ac45-51810b355b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>e3b3b525-59e4-4039-b212-e7c8ca5f3cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>4e95dbae-013a-4137-901c-c8d00b3d7e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ward is required'])[1]/preceding::select[1]</value>
      <webElementGuid>919f4c5d-da25-4d96-8045-58f3003300db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>307db0de-e6a8-4df7-a013-97348141738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>99ca41f8-fb81-4ff9-b669-6e6564e6be87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardXã Pha LongXã Tả Ngải ChồXã Tung Chung PhốThị trấn Mường KhươngXã Dìn ChinXã Tả Gia KhâuXã Nậm ChảyXã Nấm LưXã Lùng Khấu NhinXã Thanh BìnhXã Cao SơnXã Lùng VaiXã Bản LầuXã La Pan TẩnXã Tả ThàngXã Bản Sen' or . = 'Select your wardXã Pha LongXã Tả Ngải ChồXã Tung Chung PhốThị trấn Mường KhươngXã Dìn ChinXã Tả Gia KhâuXã Nậm ChảyXã Nấm LưXã Lùng Khấu NhinXã Thanh BìnhXã Cao SơnXã Lùng VaiXã Bản LầuXã La Pan TẩnXã Tả ThàngXã Bản Sen')]</value>
      <webElementGuid>6c52844f-98f0-4054-80c4-4ccf22dec563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
