<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your districtThnh ph Lo CaiHu_0d2600</name>
   <tag></tag>
   <elementGuidId>1f847ed1-a984-444c-ba31-8069146bffb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='districtCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#districtCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4217009e-cc6a-4c1e-a86f-2e07e067b1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>eb349c7e-83cd-400c-9ab6-66089962527a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>9644125d-132a-46c5-a746-05eb4880adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>22f7598f-68ea-42cc-af42-29f0a76c36ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23b5a0ca-cbeb-4601-9618-c326e1af9a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-:ra:-feedback</value>
      <webElementGuid>e85a20e6-7643-46f6-82e4-8bc41f469a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your districtThành phố Lào CaiHuyện Bát XátHuyện Mường KhươngHuyện Si Ma CaiHuyện Bắc HàHuyện Bảo ThắngHuyện Bảo YênThị xã Sa PaHuyện Văn Bàn</value>
      <webElementGuid>ddb0d69b-3855-41ba-8b9a-deb6b5d6f320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;districtCode&quot;)</value>
      <webElementGuid>0963a7b5-cd48-4034-835e-78e7d40ba7fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='districtCode']</value>
      <webElementGuid>e69182dc-4f3d-4c83-af1c-dd6fade92f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>2606a00c-cdda-4b83-a1d3-359cdf2c1fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[1]</value>
      <webElementGuid>bc1ea251-3060-4d0c-96f4-0610f63cafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Province/City'])[1]/following::select[2]</value>
      <webElementGuid>b3ba0931-5463-4ada-ae8f-dedad4eb79d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District is required'])[1]/preceding::select[1]</value>
      <webElementGuid>ba2784ff-e7f5-4cd4-8bf5-10b3e8cd8c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/preceding::select[1]</value>
      <webElementGuid>19afac4b-26fa-4b2f-a6b4-8b7db9338e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>fac1f37d-7bd7-409b-9c7d-8d4d503d008c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'districtCode' and @id = 'districtCode' and (text() = 'Select your districtThành phố Lào CaiHuyện Bát XátHuyện Mường KhươngHuyện Si Ma CaiHuyện Bắc HàHuyện Bảo ThắngHuyện Bảo YênThị xã Sa PaHuyện Văn Bàn' or . = 'Select your districtThành phố Lào CaiHuyện Bát XátHuyện Mường KhươngHuyện Si Ma CaiHuyện Bắc HàHuyện Bảo ThắngHuyện Bảo YênThị xã Sa PaHuyện Văn Bàn')]</value>
      <webElementGuid>39545c6b-c3f5-465e-beb4-e4d5bd3bf24b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
