<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Full nameMinh Minhphone0367724361Order _1de0e4</name>
   <tag></tag>
   <elementGuidId>6d97791d-3286-4123-8e86-6cd48a61e5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-161flp2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7bebe22-3fd1-422a-b9c8-466d7076a646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-161flp2</value>
      <webElementGuid>839ac6fa-e5ef-4c96-8f07-75f7b90f5413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full name:Minh Minhphone:0367724361Order Date:2:50:14 AM 07/28/2023items:Banh khoai chuoi, Banh khoai ba Khíatotal:799.345.805.940 ₫Shipping Address:1010b lê huuwc trác, Huyện Mường Nhé, Xã Chung Chải, Tỉnh Điện Biên, Việt Nam</value>
      <webElementGuid>df987341-d68e-4741-a629-5445cac33c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-19lu15j&quot;]/div[@class=&quot;css-qfdd9t&quot;]/div[@class=&quot;css-1e2iwx8&quot;]/div[@class=&quot;css-161flp2&quot;]</value>
      <webElementGuid>bc1f69e6-645b-40af-93be-4050d34f22c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>f0e1197f-e0bd-4e51-92eb-049267ae0828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank You For Your Ordering'])[1]/following::div[1]</value>
      <webElementGuid>5b16b0cc-b462-4c9e-9ed0-fa349649873a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[7]</value>
      <webElementGuid>e932fd4c-a037-4766-b45a-44431d282fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='subscribe'])[1]/preceding::div[11]</value>
      <webElementGuid>07d670a9-3a22-476c-9315-93dfbfc3334f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>b8487c6d-a810-4703-98b9-2ea73c68f4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Full name:Minh Minhphone:0367724361Order Date:2:50:14 AM 07/28/2023items:Banh khoai chuoi, Banh khoai ba Khíatotal:799.345.805.940 ₫Shipping Address:1010b lê huuwc trác, Huyện Mường Nhé, Xã Chung Chải, Tỉnh Điện Biên, Việt Nam' or . = 'Full name:Minh Minhphone:0367724361Order Date:2:50:14 AM 07/28/2023items:Banh khoai chuoi, Banh khoai ba Khíatotal:799.345.805.940 ₫Shipping Address:1010b lê huuwc trác, Huyện Mường Nhé, Xã Chung Chải, Tỉnh Điện Biên, Việt Nam')]</value>
      <webElementGuid>af42457e-9fc5-4ef8-9c81-d28015ded406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
