<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your districtThnh ph in Bin P_a20ba3</name>
   <tag></tag>
   <elementGuidId>1b67e480-ff8c-4ed4-b8bd-1e3dd31c01b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='districtCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#districtCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4cdbbc65-fbb9-490c-8921-9ac861aa6745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>d5bbccf8-8e1e-403e-a434-a7155fe8e5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>365010f7-3e15-4931-8a41-1fe748a585ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>6a0f373f-9f7e-4ee2-8392-af9ff36922d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b108fd27-84b9-4e24-a3fe-a290b3aa4705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-:rj:-feedback</value>
      <webElementGuid>b273c8ed-2d3f-43f5-93dd-f84c315d7d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your districtThành phố Điện Biên PhủThị Xã Mường LayHuyện Mường NhéHuyện Mường ChàHuyện Tủa ChùaHuyện Tuần GiáoHuyện Điện BiênHuyện Điện Biên ĐôngHuyện Mường ẢngHuyện Nậm Pồ</value>
      <webElementGuid>0449b0c5-1898-4f64-9602-bdb057fe0269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;districtCode&quot;)</value>
      <webElementGuid>e1379d0f-06d6-4647-9a2f-d1093ffd705b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='districtCode']</value>
      <webElementGuid>0a9a562b-4e84-4ca7-a908-b54100abb3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>a4ea9282-b402-4ebb-8dc1-31ff069a5d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[1]</value>
      <webElementGuid>c0832b58-9175-4a7d-93af-aca1ba5675da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Province/City'])[1]/following::select[2]</value>
      <webElementGuid>5d253e7e-9103-4d01-b74e-c5e139469e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District is required'])[1]/preceding::select[1]</value>
      <webElementGuid>b9bee408-82d5-4123-81af-e4e87bdafbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/preceding::select[1]</value>
      <webElementGuid>a8a159ce-0538-4a61-9f1b-1c132410d9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>61771571-a1af-4473-bba0-2c2f519a1bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'districtCode' and @id = 'districtCode' and (text() = 'Select your districtThành phố Điện Biên PhủThị Xã Mường LayHuyện Mường NhéHuyện Mường ChàHuyện Tủa ChùaHuyện Tuần GiáoHuyện Điện BiênHuyện Điện Biên ĐôngHuyện Mường ẢngHuyện Nậm Pồ' or . = 'Select your districtThành phố Điện Biên PhủThị Xã Mường LayHuyện Mường NhéHuyện Mường ChàHuyện Tủa ChùaHuyện Tuần GiáoHuyện Điện BiênHuyện Điện Biên ĐôngHuyện Mường ẢngHuyện Nậm Pồ')]</value>
      <webElementGuid>fe162826-8481-47f1-8de4-ac59ebc47cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
