<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardTh trn Thng NngX Cn _70b725</name>
   <tag></tag>
   <elementGuidId>4d0e93ef-278c-4ce2-84c7-e881df6fb5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08d8caff-d685-4261-860e-f31c34562c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>dbaacc71-5494-4d49-87a2-abde7d966420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>f5081bd1-ca90-4c4c-8471-0ef0bf2f057d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>19329c50-1bfc-49bd-a321-ff994cad19e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardThị trấn Thông NôngXã Cần YênXã Cần NôngXã Lương ThôngXã Đa ThôngXã Ngọc ĐộngXã Yên SơnXã Lương CanXã Thanh LongThị trấn Xuân HòaXã Lũng NặmXã Trường HàXã Cải ViênXã Nội ThônXã Tổng CọtXã Sóc HàXã Thượng ThônXã Hồng SỹXã Quý QuânXã Mã BaXã Ngọc Đào</value>
      <webElementGuid>d51de0c7-88b4-424f-99fd-53ca2e87aaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>85c3d5a2-345e-436d-b4ac-8b32df4d7d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>e7f94cbd-25e1-474e-a600-7925aca7e31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>ff190749-d91f-4a35-a0a6-bbc798059d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>6d2e2372-feed-4da5-bcfd-2c0a3916b56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>6400e85e-3c28-4ecd-91a4-a2f27a4a1bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>5b1cd444-8857-4df3-8dc5-9a83c46ee370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/preceding::select[1]</value>
      <webElementGuid>3b2c4626-1d3b-4502-8d29-f9a5adf3ba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>36f11a0a-ce1d-45df-b7d1-9c52baa41d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardThị trấn Thông NôngXã Cần YênXã Cần NôngXã Lương ThôngXã Đa ThôngXã Ngọc ĐộngXã Yên SơnXã Lương CanXã Thanh LongThị trấn Xuân HòaXã Lũng NặmXã Trường HàXã Cải ViênXã Nội ThônXã Tổng CọtXã Sóc HàXã Thượng ThônXã Hồng SỹXã Quý QuânXã Mã BaXã Ngọc Đào' or . = 'Select your wardThị trấn Thông NôngXã Cần YênXã Cần NôngXã Lương ThôngXã Đa ThôngXã Ngọc ĐộngXã Yên SơnXã Lương CanXã Thanh LongThị trấn Xuân HòaXã Lũng NặmXã Trường HàXã Cải ViênXã Nội ThônXã Tổng CọtXã Sóc HàXã Thượng ThônXã Hồng SỹXã Quý QuânXã Mã BaXã Ngọc Đào')]</value>
      <webElementGuid>8716a4a9-46ae-4366-9b0b-3b9264aed5d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
