<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardX Sn ThuX Sen ThngX _615d15</name>
   <tag></tag>
   <elementGuidId>11b01ca4-7ac0-43ae-93be-8c48e093c023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>42ed9522-fa3b-49bb-a836-5f21cf8b2d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>83c640e6-2be1-45ce-8e0a-8cefa434f6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>c363a27e-dcfb-4302-a47f-d09b06a95294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>2c5cfb36-f001-45ed-a0b0-caa199535cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c101d70-9bf0-45e1-a589-11d82bcdaac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>field-:rk:-feedback</value>
      <webElementGuid>274791df-c9ff-470e-a8db-8eae6f3c0c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardXã Sín ThầuXã Sen ThượngXã Chung ChảiXã Leng Su SìnXã Pá MỳXã Mường NhéXã Nậm VìXã Nậm KèXã Mường ToongXã Quảng LâmXã Huổi Lếnh</value>
      <webElementGuid>86bd4735-7f0e-4778-a1b8-d004a23deaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>25aa91d9-c6a0-47e8-9447-5b92e1d0fe7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>59cd58ab-73a1-419d-8ca1-b479ffbeb814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>27475797-c519-4de0-bafe-9be0ca393552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>0f73ef27-02c7-4e4a-9de4-e8ede2c441f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>f94e5d30-6887-4c40-974e-aef2f4965866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ward is required'])[1]/preceding::select[1]</value>
      <webElementGuid>1d9a6c4c-d979-4f20-821e-33059873ac1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>c25b0e84-c953-495c-9b9e-2b51fe10e6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>a3671ffc-99ed-4afd-a76f-c28a17293496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardXã Sín ThầuXã Sen ThượngXã Chung ChảiXã Leng Su SìnXã Pá MỳXã Mường NhéXã Nậm VìXã Nậm KèXã Mường ToongXã Quảng LâmXã Huổi Lếnh' or . = 'Select your wardXã Sín ThầuXã Sen ThượngXã Chung ChảiXã Leng Su SìnXã Pá MỳXã Mường NhéXã Nậm VìXã Nậm KèXã Mường ToongXã Quảng LâmXã Huổi Lếnh')]</value>
      <webElementGuid>3aa2a5f1-0ca1-4a2d-bd6e-064364319b8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
