<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your districtThnh ph Cao BngH_11cf5a</name>
   <tag></tag>
   <elementGuidId>d4809dc1-1328-4b18-a64b-db8fe6d8b740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='districtCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#districtCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6de93371-0aed-4b1d-a5dc-ca42906c0bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>21c33928-08d2-4f71-ac76-3571f643fbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>28b98e86-7f7c-4c27-8240-894256eb6c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>87016880-ce1d-49d1-9061-3dcfda56fd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An</value>
      <webElementGuid>07b210cf-87b2-417f-8b8e-f64369ffcc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;districtCode&quot;)</value>
      <webElementGuid>fa4654aa-e643-47df-9132-0931ff572f31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='districtCode']</value>
      <webElementGuid>c7b4c568-7742-454a-8e78-37acd942be06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>05989688-636a-4353-9c4a-aee416e8f880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[1]</value>
      <webElementGuid>6fdead77-ed07-492f-92d7-e286165be16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Province/City'])[1]/following::select[2]</value>
      <webElementGuid>8cf270dc-dd19-4fc9-8650-427cc6de8598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/preceding::select[1]</value>
      <webElementGuid>5227fdf5-6682-4e9e-b20b-9a0d724c9625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[2]</value>
      <webElementGuid>6c23f844-367b-4b9a-a277-f288ea544340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>ec4a2602-278d-4eb2-8e7d-4e7b0b9b008e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'districtCode' and @id = 'districtCode' and (text() = 'Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An' or . = 'Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An')]</value>
      <webElementGuid>1898af1b-cfb2-49c1-8190-a8f54b1f6445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
