<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add to cart_swiper-button-next</name>
   <tag></tag>
   <elementGuidId>0a35d64b-8006-4e0a-942b-08dcd4af9ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swiper-button-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1c0a743-4c5b-44ae-9d4e-3276b1dea3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-button-next</value>
      <webElementGuid>8a4b28f2-6ce8-4afd-9058-cbca404a7983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-12uwmyy&quot;]/div[@class=&quot;css-1p2cbqg&quot;]/div[@class=&quot;css-1a56p1a&quot;]/div[@class=&quot;css-2tc2s4&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-backface-hidden&quot;]/div[@class=&quot;swiper-button-next&quot;]</value>
      <webElementGuid>f6705dc2-8db2-4315-9bde-bf2a8e99221f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>6f48b89c-918c-4548-8898-c182d823c7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>542521ab-4c9c-4353-9b11-0132e2ef8346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
