<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You item already in shopping cart</name>
   <tag></tag>
   <elementGuidId>09ed9c8a-675f-4830-a6ef-caf5c9b6d922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-1-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-1-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>516fa1e5-6462-4111-a5f3-902c045341f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>dc9d6666-9a68-4172-9d5c-2e4ea8eb79ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-1-description</value>
      <webElementGuid>eacae207-a99c-45f2-b15a-581be99cbcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert__desc css-161kwbg</value>
      <webElementGuid>6e5edab9-7adb-4aea-b568-c39d578a97ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You item already in shopping cart</value>
      <webElementGuid>a555b6e4-c2c8-4430-aa56-970c679c66b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-1-description&quot;)</value>
      <webElementGuid>1abb8f1f-18bd-4d82-a3c0-3b75e9946cd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-1-description']</value>
      <webElementGuid>71274bdd-d5c8-4945-be43-c018628f4d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-1']/div/div[2]</value>
      <webElementGuid>0c26dda1-5d37-4d2e-9fba-bed31d98a9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successfully'])[1]/following::div[1]</value>
      <webElementGuid>7f6d15fb-a573-4732-a618-a249aa9e15e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open React Query Devtools'])[1]/following::div[8]</value>
      <webElementGuid>991b1fcd-648c-4383-abf3-c0c2d202186f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-1-description', '&quot;', ')')])[1]/preceding::div[6]</value>
      <webElementGuid>41474978-19f5-4b0d-b981-fbcac7c1d7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You item already in shopping cart']/parent::*</value>
      <webElementGuid>3b0a68cb-81e9-40dc-abd5-28a7ee09cfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>a957beae-0945-489c-be04-8a0c7095f9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-1-description' and (text() = 'You item already in shopping cart' or . = 'You item already in shopping cart')]</value>
      <webElementGuid>dc4d3296-10f4-490d-b952-c5abb1cafdcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
