<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_d_chakra-image css-lxd7e7</name>
   <tag></tag>
   <elementGuidId>ba3a8499-4d13-4f14-acd8-79db4b83cb9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.chakra-image.css-lxd7e7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div[2]/div/div[5]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32cc58fb-3f4d-45ca-892f-0fee1bf75469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-8.jpg</value>
      <webElementGuid>5b7d4301-472a-441b-a010-d09c679d1215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-image css-lxd7e7</value>
      <webElementGuid>4cc5ec93-9684-4782-b362-4ebfcf57340f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-cv59qw&quot;]/div[@class=&quot;css-yyiqbu&quot;]/div[@class=&quot;css-1w2pp6y&quot;]/div[@class=&quot;chakra-card css-e5f81e&quot;]/a[1]/div[@class=&quot;chakra-card__body css-ao8dev&quot;]/img[@class=&quot;chakra-image css-lxd7e7&quot;]</value>
      <webElementGuid>2cf4b95e-aa2e-4d60-b20d-a67964c8f0c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[2]/div/div[5]/a/div/img</value>
      <webElementGuid>97e734f8-5c76-4714-8be0-2e2781b20cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-8.jpg')]</value>
      <webElementGuid>0fbfd320-ec57-469c-bb54-5411980eed12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/img</value>
      <webElementGuid>eac8e607-156d-4437-b37b-2ca3138b894c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-8.jpg']</value>
      <webElementGuid>b2e7ceba-4136-44f0-b39a-e414f3e3f4e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
