<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Filter_chakra-image css-lxd7e7</name>
   <tag></tag>
   <elementGuidId>f4b2b682-7332-4639-b7f8-e33b2cb10727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.chakra-image.css-lxd7e7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div[2]/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d869e17c-b099-4d63-8006-cad5d3d7e032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg</value>
      <webElementGuid>1e1e3113-cc6d-458d-8c1f-81caf3f9ac28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-image css-lxd7e7</value>
      <webElementGuid>403bf7c3-16ac-4d73-bc63-ada461cb762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-cv59qw&quot;]/div[@class=&quot;css-yyiqbu&quot;]/div[@class=&quot;css-1w2pp6y&quot;]/div[@class=&quot;chakra-card css-e5f81e&quot;]/a[1]/div[@class=&quot;chakra-card__body css-ao8dev&quot;]/img[@class=&quot;chakra-image css-lxd7e7&quot;]</value>
      <webElementGuid>23220e62-69fd-47f4-a802-89cdbe81453c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[2]/div/div/a/div/img</value>
      <webElementGuid>a8cd0760-61a4-4c7f-b646-742b8a25383f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg')]</value>
      <webElementGuid>d289808c-8c17-4f0d-98ea-331ef81fbe76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>03de7676-2c68-4d32-ad8b-e2dc280a407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/wordpress/wp-content/uploads/2023/06/iphone-14-5g-smartphone-256gb-lilla-pdp_zoom-3000-pdp_main-540-388.jpg']</value>
      <webElementGuid>ebfed8c2-1a82-4340-af85-26de6ba617a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
