<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minhhonag_chakra-input css-1pdm0hx</name>
   <tag></tag>
   <elementGuidId>3948a65c-17d7-419b-b6d0-5967e22432c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chakra-input.css-1pdm0hx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f646f6ab-1e0c-4b19-933a-e1a7a2f39492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8d558ff0-b5b8-4263-9875-81494a6584ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d6a2c7a2-03dc-4a53-a1de-d85f48181e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1pdm0hx</value>
      <webElementGuid>8f0c127a-dc5b-43ca-b22b-4cf2b044c338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-1w0dmnq&quot;]/div[@class=&quot;css-1r2n8g3&quot;]/div[@class=&quot;chakra-input__group css-bx0blc&quot;]/input[@class=&quot;chakra-input css-1pdm0hx&quot;]</value>
      <webElementGuid>ebf6f26b-9118-4611-a4e4-f03d008d8cff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>b5f1673f-dccf-4f2c-a257-4d92ca49229e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>98379532-ae1a-46bf-b19e-158e58a8bacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>985c6fe2-fcd9-4de7-ae50-d071ef5ce722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>583218f3-3e86-4d6d-b2e9-cb324f4599b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
