<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Local specialtys areasThe best offer th_3515a7</name>
   <tag></tag>
   <elementGuidId>1ed81c76-897f-4a20-a24c-298894cb47a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-j74872</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd480293-42d4-42a0-9678-02152725f68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j74872</value>
      <webElementGuid>55e0ec47-6f63-4d61-9687-e4ffe804cd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local specialty's areasThe best offer that we offer to the worldallMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: sdfghertyudfghjdfghjkl </value>
      <webElementGuid>2c9c2105-b6ac-4227-80ea-b867ab691d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]</value>
      <webElementGuid>bd293bbe-4a16-4dab-8cbe-dce934999fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]</value>
      <webElementGuid>129623e7-4c0c-422b-9d9e-ab67510c49cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>9e6f6869-f011-4a9d-a895-f9690176e65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: sdfghertyudfghjdfghjkl &quot;) or . = concat(&quot;Local specialty&quot; , &quot;'&quot; , &quot;s areasThe best offer that we offer to the worldallMinhhonagFilterAllLess than 300.000 ₫From 300.000 ₫ to 800.000 ₫ More than 800.000 ₫There is no result found with keyword: sdfghertyudfghjdfghjkl &quot;))]</value>
      <webElementGuid>f9980e08-dbab-49d8-aaf2-acd1a43c554a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
