<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Filter_chakra-radio__control css-vtg3j9</name>
   <tag></tag>
   <elementGuidId>054043ba-e069-43ef-b56a-dea10e4a507c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div/label[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>338fc3f9-c1ee-446b-9cc4-cb913f742969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-radio__control css-vtg3j9</value>
      <webElementGuid>096bc0a9-d42b-4c7f-a984-95f86de1bc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>901b8ccb-8914-4854-bda4-68e90b15ba39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-16dnvck&quot;]/div[@class=&quot;css-j74872&quot;]/div[@class=&quot;css-cv59qw&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1dpkd8q&quot;]/div[@class=&quot;chakra-radio-group css-0&quot;]/div[@class=&quot;chakra-stack css-8g8ihq&quot;]/label[@class=&quot;chakra-radio css-1cqh9jq&quot;]/span[@class=&quot;chakra-radio__control css-vtg3j9&quot;]</value>
      <webElementGuid>c32343ff-b0ae-4665-937e-db361e2dcc92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div/label[3]/span</value>
      <webElementGuid>1bfb6034-8a5b-4d60-bc61-602bd4fcaab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span</value>
      <webElementGuid>d34e8216-fe61-4713-a65e-22a2ab583b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
