<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardPhng Sng HinPhng Sng_79c922</name>
   <tag></tag>
   <elementGuidId>c2d34436-13d5-4cc9-b195-99ecbb8abe4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b45f6a98-b79f-449e-92cf-c412542ea3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>2f46efef-4032-4fe1-a8e4-694ccd24946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>1a3f0bb1-3607-4b0a-ad75-8185488d4bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>234b218f-f39f-4b29-b93a-d875e077cc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardPhường Sông HiếnPhường Sông BằngPhường Hợp GiangPhường Tân GiangPhường Ngọc XuânPhường Đề ThámPhường Hoà ChungPhường Duyệt TrungXã Vĩnh QuangXã Hưng ĐạoXã Chu Trinh</value>
      <webElementGuid>6b88345c-4703-4b4b-9b92-866ee778094a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>5baf64a7-2ff6-46e3-99d6-4e9f5f174ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>4877ea4c-2c2a-49eb-be3a-12aae543168d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>405003e6-eadc-4f00-98c8-98b595ff4590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>7c5fe5a9-f3d6-453a-957e-f579998cf459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>a9e021b6-d4f5-42d8-80a8-6c7153558688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>41e45d34-4e89-4f01-82cb-934841452833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/preceding::select[1]</value>
      <webElementGuid>e8cfc964-09fd-431a-8937-3e8620f78e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>0fcd4cb6-ef80-4faf-86c4-0077b64866e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardPhường Sông HiếnPhường Sông BằngPhường Hợp GiangPhường Tân GiangPhường Ngọc XuânPhường Đề ThámPhường Hoà ChungPhường Duyệt TrungXã Vĩnh QuangXã Hưng ĐạoXã Chu Trinh' or . = 'Select your wardPhường Sông HiếnPhường Sông BằngPhường Hợp GiangPhường Tân GiangPhường Ngọc XuânPhường Đề ThámPhường Hoà ChungPhường Duyệt TrungXã Vĩnh QuangXã Hưng ĐạoXã Chu Trinh')]</value>
      <webElementGuid>ca590c3e-bed0-44e4-bc3c-482c86d7958c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
