<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your districtThnh ph Cao BngH_11cf5a</name>
   <tag></tag>
   <elementGuidId>6a51cb36-636d-45db-8e40-2f815031d429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='districtCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#districtCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b44182b-c42d-43a9-a761-aba3e461cf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>6b4ee811-760f-4449-bd6e-9d96673c804e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>districtCode</value>
      <webElementGuid>b7865143-6018-404f-b518-36d7d32ead68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>fd953517-59b9-4c9f-98d1-4350353bf074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An</value>
      <webElementGuid>0eef3170-c360-48e2-b8fa-b5e34611864b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;districtCode&quot;)</value>
      <webElementGuid>9caedb2e-6e28-4d4a-8eaf-a5ae1058171d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='districtCode']</value>
      <webElementGuid>29ff8141-e3ee-4b76-96f5-acbd0fd6e3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>d6e42cc5-f46e-4ec9-9d5b-83a473aab293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[1]</value>
      <webElementGuid>398c9e34-2c47-4909-ab84-5d7a63a6d398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Province/City'])[1]/following::select[2]</value>
      <webElementGuid>dfb5aeea-9f79-4064-9764-2c9bcc1152bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/preceding::select[1]</value>
      <webElementGuid>d07b42a9-b65e-4236-8ddf-7dce506904ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[2]</value>
      <webElementGuid>b903b7d0-e063-4b04-a540-a3f5eec1671b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>8b518971-69e7-4c6f-b7eb-e8ce75c32187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'districtCode' and @id = 'districtCode' and (text() = 'Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An' or . = 'Select your districtThành phố Cao BằngHuyện Bảo LâmHuyện Bảo LạcHuyện Hà QuảngHuyện Trùng KhánhHuyện Hạ LangHuyện Quảng HòaHuyện Hoà AnHuyện Nguyên BìnhHuyện Thạch An')]</value>
      <webElementGuid>e4e64f43-2d70-4c44-9315-abd17643ce24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
