<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardPhng Phc TnPhng ng X_75878d</name>
   <tag></tag>
   <elementGuidId>e55f54db-c526-40b5-bf48-5b549c45e86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff45822f-3882-4c1a-94a8-cc1bf6e711fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>8cfe96c9-4859-4ed8-ad65-111723a83049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>ba82d930-5ffe-450d-b61f-50ea35c5ec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>51fc10f7-5a41-4b2f-a017-7cfb24ba6bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardPhường Phúc TânPhường Đồng XuânPhường Hàng MãPhường Hàng BuồmPhường Hàng ĐàoPhường Hàng BồPhường Cửa ĐôngPhường Lý Thái TổPhường Hàng BạcPhường Hàng GaiPhường Chương DươngPhường Hàng TrốngPhường Cửa NamPhường Hàng BôngPhường Tràng TiềnPhường Trần Hưng ĐạoPhường Phan Chu TrinhPhường Hàng Bài</value>
      <webElementGuid>94c5b971-c07a-4bbd-bc39-5cd49832d5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>530d45d0-75cb-4965-89b6-ce8717947f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>183b6590-690a-4548-bd43-ff7acab43ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>0b522449-81b1-4649-bf04-dbeeded48fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>1be17340-b86d-4583-9ee0-19f8d6f4ad75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>1c6cfc33-8f04-40f5-9075-57f529c543ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>56a36b25-00e8-4888-b19c-fe019190820d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/preceding::select[1]</value>
      <webElementGuid>ba918760-ec6b-4fbd-998b-ac6f2eaa6ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>b048c879-4f9d-4b55-ba87-d07419daa98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardPhường Phúc TânPhường Đồng XuânPhường Hàng MãPhường Hàng BuồmPhường Hàng ĐàoPhường Hàng BồPhường Cửa ĐôngPhường Lý Thái TổPhường Hàng BạcPhường Hàng GaiPhường Chương DươngPhường Hàng TrốngPhường Cửa NamPhường Hàng BôngPhường Tràng TiềnPhường Trần Hưng ĐạoPhường Phan Chu TrinhPhường Hàng Bài' or . = 'Select your wardPhường Phúc TânPhường Đồng XuânPhường Hàng MãPhường Hàng BuồmPhường Hàng ĐàoPhường Hàng BồPhường Cửa ĐôngPhường Lý Thái TổPhường Hàng BạcPhường Hàng GaiPhường Chương DươngPhường Hàng TrốngPhường Cửa NamPhường Hàng BôngPhường Tràng TiềnPhường Trần Hưng ĐạoPhường Phan Chu TrinhPhường Hàng Bài')]</value>
      <webElementGuid>d1e8524e-ca14-438e-8d8f-892157d35df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
