<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your wardTh trn Bo LcX Cc Png_13a651</name>
   <tag></tag>
   <elementGuidId>dc59551a-ba80-43ae-bc5a-212f39d293f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wardCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wardCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a1baa3c-be96-4434-87ef-a657c77d4ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>456e6325-b500-40c5-a3ba-e709ab1ef7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wardCode</value>
      <webElementGuid>e1543ef8-bd4c-4c1a-8075-ba9e29ecdec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-161pkch</value>
      <webElementGuid>9a7ea606-7182-4e7b-a704-f69ba4593a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your wardThị trấn Bảo LạcXã Cốc PàngXã Thượng HàXã Cô BaXã Bảo ToànXã Khánh XuânXã Xuân TrườngXã Hồng TrịXã Kim CúcXã Phan ThanhXã Hồng AnXã Hưng ĐạoXã Hưng ThịnhXã Huy GiápXã Đình PhùngXã Sơn LậpXã Sơn Lộ</value>
      <webElementGuid>e0ba2c89-acf0-4362-bc09-42740bd34ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wardCode&quot;)</value>
      <webElementGuid>759577a5-c87d-41a7-854b-33ad96a829d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wardCode']</value>
      <webElementGuid>d91c44bd-8a3e-408e-aa79-764fb803d8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/form/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>6ea881fa-f57e-4139-bcd5-da2e665047d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your Ward'])[1]/following::select[1]</value>
      <webElementGuid>eadff7b7-4c9e-4331-94df-a310fe6892c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Your District'])[1]/following::select[2]</value>
      <webElementGuid>9d5974f8-4980-428f-a3ef-2ff8bb085b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Street'])[1]/preceding::select[1]</value>
      <webElementGuid>4787345c-1898-49a4-a460-e933e858e0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/preceding::select[1]</value>
      <webElementGuid>3479f560-1ea9-4697-aec0-a73119497b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>e5e80ef1-ad54-4db0-bfa1-1c782c1e71c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'wardCode' and @id = 'wardCode' and (text() = 'Select your wardThị trấn Bảo LạcXã Cốc PàngXã Thượng HàXã Cô BaXã Bảo ToànXã Khánh XuânXã Xuân TrườngXã Hồng TrịXã Kim CúcXã Phan ThanhXã Hồng AnXã Hưng ĐạoXã Hưng ThịnhXã Huy GiápXã Đình PhùngXã Sơn LậpXã Sơn Lộ' or . = 'Select your wardThị trấn Bảo LạcXã Cốc PàngXã Thượng HàXã Cô BaXã Bảo ToànXã Khánh XuânXã Xuân TrườngXã Hồng TrịXã Kim CúcXã Phan ThanhXã Hồng AnXã Hưng ĐạoXã Hưng ThịnhXã Huy GiápXã Đình PhùngXã Sơn LậpXã Sơn Lộ')]</value>
      <webElementGuid>b86ae1cf-2674-4cd8-bd2a-010eb4a6b8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
