<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clean cartWould you like to remove all _e6341d</name>
   <tag></tag>
   <elementGuidId>03147e01-dd84-40ae-a898-69fa50eea02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swal2-popup.swal2-modal.swal2-icon-warning.swal2-show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Open React Query Devtools'])[1]/following::div[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ae4b38a-6219-48f2-90b1-518d8589f997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>7ce8cd44-6a1f-483b-b3bf-35706ac74154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>f1886660-7260-4fa9-ab2e-c6a112136c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-popup swal2-modal swal2-icon-warning swal2-show</value>
      <webElementGuid>72c8358f-d149-4874-a26a-b424cadc7ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f1e15fe1-ffdc-4f56-9fc0-2c0321b2052a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>41ead680-1922-4857-93c6-73e6d1fefa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>92372dc2-3a91-40b1-b520-57a663d98d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>050484cd-ffeb-41a6-8f0f-40e6715cab14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×!Clean cartWould you like to remove all product?YesNoCancel</value>
      <webElementGuid>46ba7e2e-c826-4a8a-96b1-c09be2e77e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;swal2-shown swal2-height-auto&quot;]/body[@class=&quot;chakra-ui-light swal2-shown swal2-height-auto&quot;]/div[@class=&quot;swal2-container swal2-center swal2-backdrop-show&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-icon-warning swal2-show&quot;]</value>
      <webElementGuid>6a17823f-ba71-4311-9514-634f2c348962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open React Query Devtools'])[1]/following::div[11]</value>
      <webElementGuid>0b680d07-35e4-44b1-97c4-27fde5db2ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[11]</value>
      <webElementGuid>f00f74d4-77df-46f0-8b05-6c6d3758b1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>0baf1c22-ba2d-47b0-8389-b60b12953fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×!Clean cartWould you like to remove all product?YesNoCancel' or . = '×!Clean cartWould you like to remove all product?YesNoCancel')]</value>
      <webElementGuid>fd8c7c86-6d85-4f29-9a32-8bd4791650db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
