<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Account Summary</name>
   <tag></tag>
   <elementGuidId>0ccfebc1-bf1c-4c60-ba7e-fdac28f0a46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MenuHyperLink1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuHyperLink1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90600f5f-2abf-407c-9427-74d533bdf6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuHyperLink1</value>
      <webElementGuid>41bcb08e-7456-4ae5-a9b7-f4a38c67cb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bank/main.jsp</value>
      <webElementGuid>46fe5279-f845-43b3-afae-a9b32f55574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Account Summary</value>
      <webElementGuid>f07fc88a-4048-453f-bc06-052e08922560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuHyperLink1&quot;)</value>
      <webElementGuid>0f87ea12-ea5f-426b-94d7-fc7fd8096355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MenuHyperLink1']</value>
      <webElementGuid>e186fd75-67d1-4837-9f20-0c7c0b046b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Account Summary')]</value>
      <webElementGuid>678fb561-28e3-4fac-bff4-4f851a0a7187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I WANT TO ...'])[1]/following::a[1]</value>
      <webElementGuid>c442717a-1dbc-49cd-a065-3533c02fd0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSIDE ALTORO MUTUAL'])[1]/following::a[1]</value>
      <webElementGuid>688438a5-31a8-4c93-ac91-0a81f0f0edba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Recent Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>242b364a-c189-4226-af39-e5142c82eb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/preceding::a[2]</value>
      <webElementGuid>11d8ba49-32eb-49bb-823e-8e19829eee3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Account Summary']/parent::*</value>
      <webElementGuid>17d05c14-fafc-4ae3-badd-f3462ea586d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/bank/main.jsp')])[2]</value>
      <webElementGuid>dbee3b6b-dfe8-4f3b-b350-968050136898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>2957927b-a323-4e3d-ac91-6140a6a0ea92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MenuHyperLink1' and @href = '/bank/main.jsp' and (text() = 'View Account Summary' or . = 'View Account Summary')]</value>
      <webElementGuid>d67e5e2d-9832-4b75-aa21-96adf9c45e1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
